### PR TITLE
remove perlcritic -5 warnings

### PR DESCRIPTION
**Pull request by mishin**
Hi, Guys, super project,
so, I think 1 as last value of module is criitcal
and return for function

### CODE REVIEW

**Comment by karenetheridge** [comment]
These all seem like silly and unnecessary changes. A module only needs to return a true value; it doesn't need to be `1`.

**Comment by charsbar** [comment]
Thanks for requesting but I agree with Karen. Won't merge this.

**Comment by mishin** [comment]
Well, guys, I agree with you, it's very little bound, but ok.
I just want to know how calculate 
package_version_matches_dist_version
and
is_prereq
for http://cpants.cpanauthors.org/author/MISHIN

**Comment by mishin** [comment]
thanks

**Comment by charsbar** [comment]
@mishin, forget about is_prereq, which is something you can't make green by yourself (and thus, should be marked and shown differently from other metrics, maybe).

As for the package_version_matches_dist_version, it is because your version number is not safe and may lose important bit while calculating. See the following.

```
perl -E 'say version->new("5.18.1.0.35")->numify'  # 5.018001000033
perl -E 'say version->new("5.018001000033")'       # 5.018001000033
perl -E 'say version->new(5.018001000033)'         # 5.018001 (oops)
```

So, it was a bug in Module::CPANTS::SiteKwalitee, and fixed it by https://github.com/cpants/Module-CPANTS-SiteKwalitee/commit/7dd3aa61d92107178c5bd7fb5842d5da26a5f6c3 (thanks!)

**Pull request closed without merging**
