### PR TITLE
Skip everything in MANIFEST.SKIP

### PR DESCRIPTION
**Pull request by Tux**
Obviously, testing files going into the release should exclude everything
that is marked *not* going into the release

### CODE REVIEW

**Comment by charsbar** [comment]
@Tux, the current version of _make_maniskip_regex() seems not correct. Could you look at ExtUtils::Manifest::maniskip?

**Comment by Tux** [comment]
@charsbar am I allowed to use ExtUtils::Manifest to achieve this?

**Comment by Tux** [comment]
It is core since 5.001, so expect another PR :)

**Comment by charsbar** [comment]
Closed with #33

**Pull request closed without merging**
